# Generated by Django 2.1.2 on 2018-10-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_image',
            old_name='image_url',
            new_name='image',
        ),
    ]
