# Generated by Django 2.1.2 on 2018-10-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181003_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_image',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_image',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images/', width_field='image_width'),
        ),
    ]
